### ISSUE TITLE
[Request Change] old windows 10 preview cannot use powershell command given in docs. however

### ISSUE THREAD

**Issue by pokurt** [massgravel/mas-docs#1]
![image](https://user-images.githubusercontent.com/43902347/217145563-09758008-8eea-4bde-8341-bd4f1cecc693.png)

could be useful to add the following command to docs for those who have an old windows 10 preview.

**Comment by WindowsAddict** [comment]
Hi @pokurt I'm aware of this. I'll add tls 1.2 support in site itself.

**Comment by pokurt** [comment]
Thank you. we can close this Issue once the documentation is updated. thank you for the response!

**Comment by WindowsAddict** [comment]
Tls 1.0/1.1 support added in site.
